// 正面管教知识库 - 基于《正面管教》书籍内容
import { KnowledgeEntry, TaskTemplate, PhraseCard } from './types';

export const positiveDisciplineKnowledgeBase: KnowledgeEntry[] = [
  // 第1章：和善而坚定
  {
    id: 'ch1-1',
    chapter: '1',
    chapterName: '和善而坚定',
    section: '惩罚的暂时效果',
    page: '1-5',
    content: '惩罚可以立即停止不良行为，但长期效果是反叛（愤恨）、报复、反叛、退缩（偷偷摸摸或自卑）。我们应该追求的是长期有效的方法。',
    tags: ['惩罚', '长期效果', '和善', '坚定'],
  },
  {
    id: 'ch1-2',
    chapter: '1',
    chapterName: '和善而坚定',
    section: '和善与坚定相结合',
    page: '5-10',
    content: '和善的重要性在于表达对孩子的尊重。坚定的重要性在于尊重自己和情形的需要。和善而坚定是正面管教的基石。',
    tags: ['和善', '坚定', '尊重', '基础'],
  },
  {
    id: 'ch1-3',
    chapter: '1',
    chapterName: '和善而坚定',
    section: '暂停法',
    page: '10-15',
    content: '在处理冲突时，成年人可以先离开冲突现场，让自己冷静下来。这不是"暂停"，而是给孩子做榜样：尊重自己，等情绪平静后再处理问题。',
    tags: ['暂停', '冷静', '榜样', '情绪管理'],
  },

  // 第2章：理解行为背后的信念
  {
    id: 'ch2-1',
    chapter: '2',
    chapterName: '理解行为背后的信念',
    section: '错误目的表',
    page: '20-35',
    content: '孩子所有行为都有一个目的。四个错误目的是：寻求过度关注、寻求权力、报复、自暴自弃。每个错误目的都有不同的线索和反应策略。',
    tags: ['错误目的', '信念', '行为目的', '四大错误目的'],
  },
  {
    id: 'ch2-2',
    chapter: '2',
    chapterName: '理解行为背后的信念',
    section: '自暴自弃',
    page: '30-35',
    content: '"别惹我"和"我不能"是自暴自弃孩子的典型特征。这些孩子相信"我不重要，没人喜欢我"。他们需要的是具体的帮助和鼓励，而不是批评。',
    tags: ['自暴自弃', '鼓励', '低自尊', '需要帮助'],
  },
  {
    id: 'ch2-3',
    chapter: '2',
    chapterName: '理解行为背后的信念',
    section: '错误目的的识别',
    page: '35-45',
    content: '识别孩子错误目的的线索：1）家长 feelings when behavior occurs 2）孩子对家长行为的反应 3）错误目的的线索（请求、反抗、伤害、冷漠）',
    tags: ['识别', '线索', '反应', '错误目的表'],
  },

  // 第3章：出生顺序
  {
    id: 'ch3-1',
    chapter: '3',
    chapterName: '出生顺序',
    section: '独生子',
    page: '50-55',
    content: '独生子可能培养出追求卓越或完美主义的性格。他们通常有很高的期望，需要学习失败是可以接受的。',
    tags: ['独生子', '完美主义', '期望', '出生顺序'],
  },

  // 第4章：发展适应性行为
  {
    id: 'ch4-1',
    chapter: '4',
    chapterName: '发展适应性行为',
    section: '重新开始',
    page: '60-65',
    content: '当你处于"原始脑"状态时，最好的办法是平静地离开，去"重新开始"。告诉孩子："我需要冷静一下，等我们都平静下来再谈。"这不是放弃，而是尊重自己和孩子。',
    tags: ['重新开始', '冷静', '原始脑', '情绪调节'],
  },
  {
    id: 'ch4-2',
    chapter: '4',
    chapterName: '发展适应性行为',
    section: '3R1H',
    page: '65-70',
    content: '3R1H 工具：相关(Related)、尊重(Respectful)、合理(Reasonable)、有帮助(Helpful)。这是纠正错误的核心理念。',
    tags: ['3R1H', '纠正错误', '核心理念'],
  },

  // 第5章：专注于解决问题
  {
    id: 'ch5-1',
    chapter: '5',
    chapterName: '专注于解决问题',
    section: '积极的暂停',
    page: '80-85',
    content: '积极的暂停不是惩罚，而是帮助孩子冷静下来的机会。可以和孩子一起创建一个"冷静角"，让孩子参与选择和布置。',
    tags: ['积极暂停', '冷静角', '情绪调节'],
  },
  {
    id: 'ch5-2',
    chapter: '5',
    chapterName: '专注于解决问题',
    section: '启发式问题',
    page: '85-95',
    content: '启发式问题的关键是：不要急于给出答案。问"发生了什么？""你觉得原因是什么？""下次可以怎么做？""你从中学到了什么？"',
    tags: ['启发式提问', '引导', '自主思考'],
  },

  // 第6章：家庭会议
  {
    id: 'ch6-1',
    chapter: '6',
    chapterName: '家庭会议',
    section: '家庭会议流程',
    page: '100-110',
    content: '家庭会议的核心环节：1）致谢（感激）2）议程 3）头脑风暴 4）选择解决问题的方案 5）娱乐活动 6）结束时的甜点水果。',
    tags: ['家庭会议', '流程', '致谢', '头脑风暴'],
  },
  {
    id: 'ch6-2',
    chapter: '6',
    chapterName: '家庭会议',
    section: '致谢环节',
    page: '105-108',
    content: '每次会议开始时，每人轮流说出对其他家庭成员的感谢。这培养感恩之心，增强家庭凝聚力。',
    tags: ['致谢', '感激', '家庭氛围'],
  },
  {
    id: 'ch6-3',
    chapter: '6',
    chapterName: '家庭会议',
    section: '头脑风暴',
    page: '108-115',
    content: '头脑风暴规则：1）不批评、2）数量越多越好、3）疯狂的想法也可以、4）组合和改进想法。把评判留到后面。',
    tags: ['头脑风暴', '创意', '无批评', '解决方案'],
  },

  // 第7章：综合应用
  {
    id: 'ch7-1',
    chapter: '7',
    chapterName: '综合应用',
    section: '日常惯例表',
    page: '120-125',
    content: '日常惯例表让孩子参与制作日程安排，减少权力之争。关键是不用提醒，只需要问："你的惯例表上接下来是什么？"',
    tags: ['日常惯例', '惯例表', '减少权力之争', '自主'],
  },
  {
    id: 'ch7-2',
    chapter: '7',
    chapterName: '综合应用',
    section: '无言信号',
    page: '125-130',
    content: '创建一个秘密的无言信号系统，比如摸耳朵表示"我爱你"，手指点嘴唇表示"我需要你安静"。这比唠叨和提醒更有效。',
    tags: ['无言信号', '暗号', '无声沟通'],
  },
  {
    id: 'ch7-3',
    chapter: '7',
    chapterName: '综合应用',
    section: '班会',
    page: '130-140',
    content: '班会让孩子参与制定规则，培养责任感和问题解决能力。每月一次家庭会议，每周一次班会。',
    tags: ['班会', '规则制定', '参与', '责任感'],
  },

  // 第8章：正面管教工具
  {
    id: 'ch8-1',
    chapter: '8',
    chapterName: '正面管教工具',
    section: '赢得合作的四个步骤',
    page: '145-150',
    content: '赢得合作的四个步骤：1）表达理解："我知道你很生气/沮丧" 2）表达同情："我也有过类似感受" 3）分享你的感受："但我担心的是..." 4）关注解决问题："你觉得我们怎么解决？"',
    tags: ['赢得合作', '四个步骤', '共情', '解决问题'],
  },
  {
    id: 'ch8-2',
    chapter: '8',
    chapterName: '正面管教工具',
    section: '鼓励与表扬',
    page: '150-155',
    content: '表扬是评价性的（"你真聪明"），鼓励是欣赏性的（"你的努力有回报了"）。鼓励帮助孩子建立自信，表扬可能导致孩子依赖外部认可。',
    tags: ['鼓励', '表扬', '自尊', '内在动力'],
  },
  {
    id: 'ch8-3',
    chapter: '8',
    chapterName: '正面管教工具',
    section: '错误是学习的好机会',
    page: '155-160',
    content: '把错误当作学习机会，而不是失败。问孩子："你从这次经历中学到了什么？""下次可以怎么做得不同？"帮助孩子把挫折转化为成长。',
    tags: ['错误', '学习机会', '成长', '反思'],
  },

  // 第9章：情绪管理
  {
    id: 'ch9-1',
    chapter: '9',
    chapterName: '情绪管理',
    section: '感受无对错',
    page: '165-170',
    content: '感受没有对错之分。允许孩子表达情绪，但行为有对错之分。我们可以说："你可以生气，但不能用这种方式表达。"',
    tags: ['情绪', '感受', '表达', '界限'],
  },
  {
    id: 'ch9-2',
    chapter: '9',
    chapterName: '情绪管理',
    section: '情绪诚实',
    page: '170-175',
    content: '家长要学会诚实地表达自己的感受，这为孩子树立榜样。"当我看到你房间这么乱，我感到沮丧，因为我需要整洁的环境。"',
    tags: ['情绪诚实', '表达感受', '榜样', '诚实'],
  },

  // 第10章：其他挑战
  {
    id: 'ch10-1',
    chapter: '10',
    chapterName: '其他挑战',
    section: '拒绝上学',
    page: '180-190',
    content: '孩子拒绝上学可能有多种原因：分离焦虑、社交困难、学业压力、被欺负。父母需要耐心了解原因，而不是强迫或惩罚。',
    tags: ['拒绝上学', '分离焦虑', '理解', '支持'],
  },
  {
    id: 'ch10-2',
    chapter: '10',
    chapterName: '其他挑战',
    section: '权力之争',
    page: '190-195',
    content: '权力之争的迹象：家长感到被挑战、愤怒、受伤。解决方案：退出斗争、改变自己、给有限的选择、召开家庭会议。',
    tags: ['权力之争', '愤怒', '退出', '选择'],
  },

  // 附录：实用话术
  {
    id: 'app-1',
    chapter: '附录',
    chapterName: '实用话术',
    section: '日常对话',
    page: '200-210',
    content: '实用开场白："我注意到你...（描述观察到的行为）。""我很好奇，是什么让你...？""我需要你的帮助。""我们一起想办法。"',
    tags: ['话术', '开场白', '日常', '对话'],
  },
];

// 默认任务模板
export const defaultTaskTemplates: TaskTemplate[] = [
  // 早晨
  {
    id: 'morning-1',
    period: 'morning',
    title: '起床问候',
    description: '用正面语言叫醒孩子，如"美好的一天开始了，你需要我抱抱还是自己起床？"',
    icon: 'sun',
  },
  {
    id: 'morning-2',
    period: 'morning',
    title: '穿衣整理',
    description: '给孩子有限选择："你想先穿衣服还是先刷牙？"',
    icon: 'shirt',
  },
  {
    id: 'morning-3',
    period: 'morning',
    title: '早餐时光',
    description: '让孩子参与准备："你想帮忙摆碗筷还是准备水果？"',
    icon: 'utensils',
  },
  // 日间
  {
    id: 'afternoon-1',
    period: 'afternoon',
    title: '放学回家',
    description: '情感联结时刻："我好想你！今天发生了什么开心的事吗？"',
    icon: 'home',
  },
  {
    id: 'afternoon-2',
    period: 'afternoon',
    title: '作业时间',
    description: '使用惯例表："作业时间到了，你的惯例表上第一项是什么？"',
    icon: 'book',
  },
  {
    id: 'afternoon-3',
    period: 'afternoon',
    title: '自由活动',
    description: '给孩子自主选择："你有30分钟自由时间，你想做什么？"',
    icon: 'play',
  },
  // 晚间
  {
    id: 'evening-1',
    period: 'evening',
    title: '晚餐准备',
    description: '邀请参与："晚餐需要小帮手，你愿意帮忙吗？"',
    icon: 'chef-hat',
  },
  {
    id: 'evening-2',
    period: 'evening',
    title: '睡前分享',
    description: '特别时光："我们聊聊今天的开心事和挑战吧。"',
    icon: 'moon',
  },
  {
    id: 'evening-3',
    period: 'evening',
    title: '道晚安',
    description: '爱的表达："我爱你。晚安。"（无言信号：摸耳朵）',
    icon: 'heart',
  },
];

// 默认话术卡片
export const defaultPhraseCards: PhraseCard[] = [
  // 赢得合作
  {
    id: 'phrase-1',
    category: '赢得合作',
    title: '表达理解',
    content: '我知道你很生气/沮丧/难过。',
    situation: '孩子情绪激动时，先表达理解',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['共情', '理解', '情绪'],
  },
  {
    id: 'phrase-2',
    category: '赢得合作',
    title: '表达同情',
    content: '我也有过类似的感觉，当我也...的时候。',
    situation: '建立连接，表明我们也有类似经历',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['共情', '连接', '分享'],
  },
  {
    id: 'phrase-3',
    category: '赢得合作',
    title: '分享感受',
    content: '但我担心的是...，因为...',
    situation: '在理解之后，表达家长的感受',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['表达感受', '担忧', '原因'],
  },
  {
    id: 'phrase-4',
    category: '赢得合作',
    title: '关注解决',
    content: '你觉得我们怎么解决这个问题？',
    situation: '邀请孩子参与解决',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['解决问题', '邀请', '合作'],
  },
  // 启发式提问
  {
    id: 'phrase-5',
    category: '启发式提问',
    title: '了解情况',
    content: '发生了什么事？',
    situation: '不预设答案开放式提问',
    sourceChapter: '第5章',
    isFavorite: false,
    tags: ['开放', '了解', '不预判'],
  },
  {
    id: 'phrase-6',
    category: '启发式提问',
    title: '探究原因',
    content: '你觉得为什么会有这种事情发生？',
    situation: '帮助孩子反思原因',
    sourceChapter: '第5章',
    isFavorite: false,
    tags: ['原因', '反思', '分析'],
  },
  {
    id: 'phrase-7',
    category: '启发式提问',
    title: '展望未来',
    content: '下次遇到这种情况，你可以怎么做？',
    situation: '培养解决问题的能力',
    sourceChapter: '第5章',
    isFavorite: false,
    tags: ['未来', '解决方案', '预防'],
  },
  {
    id: 'phrase-8',
    category: '启发式提问',
    title: '学习收获',
    content: '你从中学到了什么？',
    situation: '把错误变成学习机会',
    sourceChapter: '第5章',
    isFavorite: false,
    tags: ['学习', '成长', '反思'],
  },
  // 积极暂停
  {
    id: 'phrase-9',
    category: '积极暂停',
    title: '冷静提议',
    content: '我们都需要冷静一下，等准备好了再谈。',
    situation: '双方情绪激动时',
    sourceChapter: '第5章',
    isFavorite: false,
    tags: ['冷静', '暂停', '重新开始'],
  },
  {
    id: 'phrase-10',
    category: '积极暂停',
    title: '使用暗号',
    content: '（无言信号：摸耳朵 = 我爱你）',
    situation: '创建属于你们的暗号系统',
    sourceChapter: '第7章',
    isFavorite: false,
    tags: ['暗号', '无言', '信号'],
  },
  // 情绪调节
  {
    id: 'phrase-11',
    category: '情绪调节',
    title: '接纳情绪',
    content: '你有权利感到生气/难过/沮丧。',
    situation: '肯定孩子的感受是合理的',
    sourceChapter: '第9章',
    isFavorite: false,
    tags: ['接纳', '情绪', '肯定'],
  },
  {
    id: 'phrase-12',
    category: '情绪调节',
    title: '区分感受与行为',
    content: '你可以感到生气，但打人不可以。',
    situation: '区分感受和行为',
    sourceChapter: '第9章',
    isFavorite: false,
    tags: ['感受', '行为', '界限'],
  },
  // 错误目的
  {
    id: 'phrase-13',
    category: '错误目的',
    title: '应对自暴自弃',
    content: '我看到你很努力，我为你骄傲。哪怕只是一小步，也是一大步。',
    situation: '孩子表现出放弃行为时',
    sourceChapter: '第2章',
    isFavorite: false,
    tags: ['鼓励', '自暴自弃', '肯定努力'],
  },
  {
    id: 'phrase-14',
    category: '错误目的',
    title: '应对寻求权力',
    content: '我注意到你在挑战我的权威。让我们暂停一下，等我们都冷静了再来解决。',
    situation: '权力之争时',
    sourceChapter: '第10章',
    isFavorite: false,
    tags: ['权力', '退出', '冷静'],
  },
  // 日常惯例
  {
    id: 'phrase-15',
    category: '日常惯例',
    title: '惯例表引导',
    content: '你的惯例表上接下来是什么？',
    situation: '代替唠叨和提醒',
    sourceChapter: '第7章',
    isFavorite: false,
    tags: ['惯例表', '引导', '自主'],
  },
  {
    id: 'phrase-16',
    category: '日常惯例',
    title: '有限选择',
    content: '你想穿红色的还是蓝色的衣服？',
    situation: '给予适当的选择权',
    sourceChapter: '第7章',
    isFavorite: false,
    tags: ['选择', '自主', '有限'],
  },
  // 家庭会议
  {
    id: 'phrase-17',
    category: '家庭会议',
    title: '致谢开场',
    content: '我想对___说声谢谢，因为___。',
    situation: '家庭会议致谢环节',
    sourceChapter: '第6章',
    isFavorite: false,
    tags: ['致谢', '感激', '家庭会议'],
  },
  {
    id: 'phrase-18',
    category: '家庭会议',
    title: '头脑风暴',
    content: '好主意！我们把所有想法都写下来，之后再评估。',
    situation: '头脑风暴阶段',
    sourceChapter: '第6章',
    isFavorite: false,
    tags: ['头脑风暴', '创意', '不批评'],
  },
  // 鼓励话语
  {
    id: 'phrase-19',
    category: '鼓励话语',
    title: '描述性鼓励',
    content: '我看到你___（具体行为）。这说明你___（品格）。',
    situation: '描述孩子的具体行为和品格',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['鼓励', '具体', '品格'],
  },
  {
    id: 'phrase-20',
    category: '鼓励话语',
    title: '感激鼓励',
    content: '谢谢你___（具体帮助）。这让我感到___（感受）。',
    situation: '表达感激而非评价',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['感激', '具体', '感受'],
  },
];

// 默认孩子档案
export const defaultChildProfile = {
  id: 'child-1',
  name: '小明',
  birthDate: '2018-03-15',
  gender: 'male' as const,
  currentStage: '幼儿园' as const,
  keyBehaviors: [],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
