// 正面管教知识库 - 基于《正面管教》书籍内容（由PDF提取）
import { KnowledgeEntry, TaskTemplate, PhraseCard } from './types';

export const positiveDisciplineKnowledgeBase: KnowledgeEntry[] = [
  // ========== 第一章：正面的方法 ==========
  {
    id: 'ch1-1',
    chapter: '1',
    chapterName: '正面的方法',
    section: '三种互动方式',
    page: '1-10',
    content: '大人与孩子之间有三种主要互动方式：1）严厉型：有规矩但没有自由，"我要你怎么做，你就得怎么做"；2）娇纵型：有自由但没有规矩，"你想怎么做，就怎么做"；3）正面管教型：有规矩也有自由，"在尊重别人的前提下，你可以选择"。',
    tags: ['三种方式', '严厉', '娇纵', '正面管教'],
  },
  {
    id: 'ch1-2',
    chapter: '1',
    chapterName: '正面的方法',
    section: '惩罚的长期效果',
    page: '10-15',
    content: '惩罚造成的四个R：1）愤恨（Resentment）——"这不公平！我不能相信大人！"；2）报复（Revenge）——"这回他们赢了，但我会扳回来的！"；3）反叛（Rebellion）——"我偏要对着干"；4）退缩（Retreat）——偷偷摸摸或自卑。',
    tags: ['惩罚', '长期效果', '四个R', '愤恨', '报复', '反叛', '退缩'],
  },
  {
    id: 'ch1-3',
    chapter: '1',
    chapterName: '正面的方法',
    section: '和善与坚定并行',
    page: '15-20',
    content: '和善的重要性在于表达对孩子的尊重。坚定的重要性在于尊重自己和情形的需要。和善而坚定是正面管教的基石，意味着对孩子和大人都有尊严和尊重。',
    tags: ['和善', '坚定', '尊重', '尊严'],
  },
  {
    id: 'ch1-4',
    chapter: '1',
    chapterName: '正面的方法',
    section: '七项重要的感知力和技能',
    page: '20-25',
    content: '成为一个有能力的人所必需的"七项重要的感知力和技能"：1）对个人能力的感知力——"我能行"；2）对自己在重要关系中的价值的感知力——"我的贡献有价值"；3）对自己在生活中的力量或影响的感知力——"我能影响发生在自己身上的事情"；4）内省能力强；5）很强的人际沟通能力；6）整体把握能力强；7）判断能力强。',
    tags: ['七项技能', '能力', '感知力', '内省', '沟通'],
  },
  {
    id: 'ch1-5',
    chapter: '1',
    chapterName: '正面的方法',
    section: '培养责任感',
    page: '25-30',
    content: '当成年人太严格和控制过多时，孩子们培养不出责任感；当对孩子娇纵时，孩子也培养不出责任感。孩子的责任感只有在和善而坚定、有尊严、受尊重的氛围中，才有机会培养出来。',
    tags: ['责任感', '培养', '氛围', '机会'],
  },

  // ========== 第二章：几个基本概念 ==========
  {
    id: 'ch2-1',
    chapter: '2',
    chapterName: '几个基本概念',
    section: '自尊',
    page: '30-35',
    content: '自尊是孩子体验到自己的价值感。不要把孩子的自尊建立在家长或老师的评判之上。培养孩子自尊的正确方式是让他们参与问题的解决过程，而不是替他们做。',
    tags: ['自尊', '价值感', '培养', '评判'],
  },
  {
    id: 'ch2-2',
    chapter: '2',
    chapterName: '几个基本概念',
    section: '赢得孩子',
    page: '35-40',
    content: '"赢得"孩子意味着你用尊重的方式让孩子心甘情愿地与你合作。当你"赢了"孩子时，孩子会感到被理解、被欣赏；当孩子感到被理解时，他们才会愿意合作。',
    tags: ['赢得', '合作', '尊重', '理解'],
  },
  {
    id: 'ch2-3',
    chapter: '2',
    chapterName: '几个基本概念',
    section: '我们言行背后的感觉',
    page: '40-45',
    content: '我们说话的语气和态度往往比话语本身更重要。问问自己：我现在的语气是在建立信任还是摧毁信任？是在鼓励还是羞辱？是基于恐惧还是基于信任？',
    tags: ['语气', '态度', '信任', '鼓励'],
  },
  {
    id: 'ch2-4',
    chapter: '2',
    chapterName: '几个基本概念',
    section: '阿德勒的基本概念',
    page: '45-55',
    content: '阿德勒的核心观点：1）孩子是社会人；2）行为是以在一定的环境下追求归属感和价值感为目的的；3）一个行为不当的孩子是一个丧失信心的孩子；4）社会责任感是人生的头等大事。',
    tags: ['阿德勒', '归属感', '价值感', '社会责任感'],
  },
  {
    id: 'ch2-5',
    chapter: '2',
    chapterName: '几个基本概念',
    section: '犯错误是学习的好机会',
    page: '55-60',
    content: '我们从小得到的教育是要为犯错误而羞愧。实际上，犯错误是学习的好机会。我们要做的是"矫正错误的三个R"：1）承认（Recognize）——"我犯了一个错误"；2）和好（Reconcile）——"我向你道歉"；3）解决（Resolve）——"让我们一起解决问题"。',
    tags: ['错误', '学习', '矫正错误', '三个R', '道歉'],
  },

  // ========== 第三章：重新看待不良行为 ==========
  {
    id: 'ch3-1',
    chapter: '3',
    chapterName: '重新看待不良行为',
    section: '四个错误观念和错误行为目的',
    page: '60-70',
    content: '孩子所有行为背后都有四个错误观念：1）寻求过度关注——"我只有得到关注才有归属感"；2）寻求权力——"我只有证明我说了算才有归属感"；3）报复——"我只有让你受伤才公平"；4）自暴自弃——"我不可能有归属感，所以我放弃"。',
    tags: ['四个错误目的', '错误观念', '归属感', '寻求关注', '寻求权力', '报复', '自暴自弃'],
  },
  {
    id: 'ch3-2',
    chapter: '3',
    chapterName: '重新看待不良行为',
    section: '错误目的表-寻求关注',
    page: '70-75',
    content: '寻求过度关注的孩子：表现包括命令、抱怨、坚持、惹人恼怒。家长感受：烦、恼怒、担忧、内疚。孩子目的：获得关注。应对方法：给孩子提供建设性的关注任务，或安排特别时光。',
    tags: ['寻求关注', '命令', '抱怨', '特别时光'],
  },
  {
    id: 'ch3-3',
    chapter: '3',
    chapterName: '重新看待不良行为',
    section: '错误目的表-寻求权力',
    page: '75-80',
    content: '寻求权力的孩子：表现包括对抗、不服从、顶嘴、故意做对。家长感受：被挑战、愤怒、受伤、害怕。孩子的目的：证明自己说了算。应对方法：退出冲突，提供有限选择，让孩子参与制定规则。',
    tags: ['寻求权力', '对抗', '愤怒', '有限选择'],
  },
  {
    id: 'ch3-4',
    chapter: '3',
    chapterName: '重新看待不良行为',
    section: '错误目的表-报复',
    page: '80-85',
    content: '报复的孩子：表现包括伤害、毁坏、偷东西、报复。家长感受：失望、觉得被伤害、愤怒。孩子的目的：感到公平。应对方法：保持友善，说出你的感受，倾听，共情。',
    tags: ['报复', '伤害', '失望', '共情'],
  },
  {
    id: 'ch3-5',
    chapter: '3',
    chapterName: '重新看待不良行为',
    section: '错误目的表-自暴自弃',
    page: '85-90',
    content: '自暴自弃的孩子：表现包括退缩、拒绝、毫无反应。家长的感受：绝望、无望、无助。孩子的目的：放弃。应对方法：表达对孩子的信任，安排简单的任务，避免过度帮助，鼓励小的进步。',
    tags: ['自暴自弃', '退缩', '绝望', '鼓励', '信任'],
  },
  {
    id: ' ch3-6',
    chapter: '3',
    chapterName: '重新看待不良行为',
    section: '目的揭示法',
    page: '90-95',
    content: '目的揭示法可以帮助孩子认识自己的错误目的：1）问孩子是否知道自己的目的；2）确认孩子的感受；3）说出你的理解和猜测；4）请孩子验证你的猜测。这需要温和和真诚的态度。',
    tags: ['目的揭示', '认识', '猜测', '验证'],
  },

  // ========== 第四章：关注于解决问题 ==========
  {
    id: 'ch4-1',
    chapter: '4',
    chapterName: '关注于解决问题',
    section: '3R1H',
    page: '95-100',
    content: '关注于解决问题的3R1H：1）相关（Related）——与当前情况有关；2）尊重（Respectful）——对所有相关人员都尊重；3）合理（Reasonable）——在常理范围内；4）有帮助（Helpful）——有助于问题的解决。',
    tags: ['3R1H', '解决问题', '相关', '尊重', '合理', '有帮助'],
  },
  {
    id: 'ch4-2',
    chapter: '4',
    chapterName: '关注于解决问题',
    section: '积极的暂停',
    page: '100-105',
    content: '积极的暂停不是惩罚，而是帮助孩子冷静下来。可与孩子一起创建一个"冷静角"，让孩子参与选择和布置。关键是教孩子理解暂停的目的是帮助自己感觉好起来，而不是逃避。',
    tags: ['积极暂停', '冷静', '冷静角', '感觉好起来'],
  },
  {
    id: 'ch4-3',
    chapter: '4',
    chapterName: '关注于解决问题',
    section: '启发式问题',
    page: '105-110',
    content: '启发式问题的关键是不要急于给出答案。经典问题：1）"发生了什么事？"；2）"你当时有什么感受？"；3）"你觉得原因是什么？"；4）"下次可以怎么做？"；5）"你从中学到了什么？"',
    tags: ['启发式提问', '引导', '自主思考', '反思'],
  },
  {
    id: 'ch4-4',
    chapter: '4',
    chapterName: '关注于解决问题',
    section: '解决问题的步骤',
    page: '110-115',
    content: '解决问题的步骤：1）停一停，等情绪平静；2）心平气和地讨论，收集双方想法；3）头脑风暴解决方案；4）选择所有人都同意的方案；5）执行并回顾效果。',
    tags: ['解决问题', '步骤', '头脑风暴', '回顾'],
  },

  // ========== 第五章：班会 ==========
  {
    id: 'ch5-1',
    chapter: '5',
    chapterName: '班会',
    section: '班会的目的',
    page: '115-120',
    content: '班会的三个目的：1）培养七项重要的感知力和技能；2）学会倾听；3）提交问题的能力。把错误当作学习的机会，而非惩罚的对象。',
    tags: ['班会', '目的', '倾听', '七项技能'],
  },
  {
    id: 'ch5-2',
    chapter: '5',
    chapterName: '班会',
    section: '班会的指导原则',
    page: '120-125',
    content: '成功班会的态度和指导原则：1）排除一切惩罚；2）表现出对每个孩子的尊重；3）问启发式问题；4）要赢得孩子们的心，而不是赢了孩子们；5）关注"解决方案"而非"后果"。',
    tags: ['班会原则', '尊重', '启发式', '解决方案'],
  },
  {
    id: 'ch5-3',
    chapter: '5',
    chapterName: '班会',
    section: '班会指南',
    page: '125-130',
    content: '班会组织流程：1）开场致谢（围圈）；2）宣读议程；3）讨论问题；4）头脑风暴；5）选择解决方案；6）总结和感谢。',
    tags: ['班会流程', '致谢', '头脑风暴', '总结'],
  },

  // ========== 第六章：家庭会议 ==========
  {
    id: 'ch6-1',
    chapter: '6',
    chapterName: '家庭会议',
    section: '家庭会议的意义',
    page: '130-135',
    content: '家庭会议是《正面管教》最有力的工具之一。它能教会孩子社会技能、培养责任感、解决问题的能力，同时增强家庭凝聚力。',
    tags: ['家庭会议', '意义', '凝聚力', '责任感'],
  },
  {
    id: 'ch6-2',
    chapter: '6',
    chapterName: '家庭会议',
    section: '家庭会议的构件',
    page: '135-140',
    content: '家庭会议的核心构件：1）致谢/感激——每人说出对其他家庭成员的感谢；2）议程——讨论需要解决的问题；3）头脑风暴——收集所有建议；4）选择方案——达成共识；5）娱乐活动——以愉快结束；6）甜点/水果——作为仪式感。',
    tags: ['家庭会议', '构件', '致谢', '头脑风暴', '娱乐'],
  },
  {
    id: 'ch6-3',
    chapter: '6',
    chapterName: '家庭会议',
    section: '致谢环节',
    page: '140-145',
    content: '致谢是家庭会议最重要的环节。格式："我想感谢__，因为__。" 这培养感恩之心，让孩子学会欣赏他人，营造积极的家庭氛围。',
    tags: ['致谢', '感激', '感恩', '欣赏'],
  },
  {
    id: 'ch6-4',
    chapter: '6',
    chapterName: '家庭会议',
    section: '头脑风暴规则',
    page: '145-150',
    content: '头脑风暴的规则：1）不许批评——把评判留到后面；2）数量越多越好——疯狂的想法也可以；3）组合和改进——鼓励"好，还有呢？"',
    tags: ['头脑风暴', '规则', '不批评', '创意'],
  },
  {
    id: 'ch6-5',
    chapter: '6',
    chapterName: '家庭会议',
    section: '计划娱乐活动',
    page: '150-155',
    content: '家庭会议最后以一个有趣的娱乐活动结束。可以提前计划下周的家庭活动。让孩子参与计划，培养家庭归属感。',
    tags: ['娱乐', '活动', '计划', '归属感'],
  },

  // ========== 第七章：综合应用 ==========
  {
    id: 'ch7-1',
    chapter: '7',
    chapterName: '综合应用',
    section: '卫生间使用技巧',
    page: '155-160',
    content: '卫生间使用技巧：当冲突升级时，独自去卫生间冷静。这不是逃避，而是给彼此空间。当感觉自己要失控时，说"我需要冷静一下"然后离开。',
    tags: ['卫生间', '冷静', '空间', '暂停'],
  },
  {
    id: 'ch7-2',
    chapter: '7',
    chapterName: '综合应用',
    section: '小说的使用技巧',
    page: '160-165',
    content: '可以用"小说"的方式描述孩子的行为，而不是直接批评。"我看到一个小朋友在发脾气"比"你在发脾气"更有效，因为它避免了指责。',
    tags: ['小说技巧', '描述', '观察', '非指责'],
  },
  {
    id: 'ch7-3',
    chapter: '7',
    chapterName: '综合应用',
    section: '日常惯例表',
    page: '165-170',
    content: '日常惯例表是减少权力之争的神器。让孩子参与制作日程表，然后问"你的惯例表上接下来是什么？"而不是唠叨和提醒。关键是让孩子自己管理自己的时间。',
    tags: ['日常惯例', '惯例表', '权力之争', '自我管理'],
  },
  {
    id: 'ch7-4',
    chapter: '7',
    chapterName: '综合应用',
    section: '无言的信号',
    page: '170-175',
    content: '创建一个秘密的无言信号系统，比如摸耳朵表示"我爱你"，手指点嘴唇表示"我需要你安静"。这比唠叨和提醒更有效，且不会让孩子感到被当众批评。',
    tags: ['无言信号', '暗号', '无声沟通'],
  },
  {
    id: 'ch7-5',
    chapter: '7',
    chapterName: '综合应用',
    section: '睡前分享',
    page: '175-180',
    content: '睡前分享时光是建立亲密关系的黄金时间。可以问："今天有什么让你开心的事？有什么让你烦恼的事？需要我帮忙吗？" 简短但有意义的交流。',
    tags: ['睡前分享', '亲密', '交流', '烦恼'],
  },
  {
    id: 'ch7-6',
    chapter: '7',
    chapterName: '综合应用',
    section: '避免早晨的麻烦',
    page: '180-185',
    content: '解决早晨混乱的方法：1）前一天晚上准备好第二天的东西；2）制定早晨惯例表；3）让孩子参与准备早餐；4）设定时间限制和后果。保持和善而坚定。',
    tags: ['早晨', '惯例', '准备', '后果'],
  },
  {
    id: 'ch7-7',
    chapter: '7',
    chapterName: '综合应用',
    section: '避免就寝时的争斗',
    page: '185-190',
    content: '睡前争斗的解决：1）建立固定的睡前惯例；2）让孩子参与选择睡衣、讲故事的数量等；3）使用计时器；4）提供有限选择；5）以特别时光结束。',
    tags: ['就寝', '睡前', '惯例', '争斗'],
  },
  {
    id: 'ch7-8',
    chapter: '7',
    chapterName: '综合应用',
    section: '给孩子提供选择',
    page: '190-195',
    content: '有限选择的力量：1）选择要与孩子年龄相称；2）选项要合理可行；3）不要在选择中包含你不想给的东西；4）当孩子做出选择后，尊重他的决定。',
    tags: ['选择', '有限选择', '自主', '尊重'],
  },

  // ========== 第八章：家里和教室里的爱与欢乐 ==========
  {
    id: 'ch8-1',
    chapter: '8',
    chapterName: '爱与欢乐',
    section: '三个提醒',
    page: '195-200',
    content: '三个提醒：1）我们做什么不如我们怎么做更重要——你的行为比话语更有说服力；2）言辞要谨慎——说出的话要能表达真正的爱；3）进入孩子的世界——用他们的眼睛看世界。',
    tags: ['提醒', '行为', '言辞', '爱'],
  },
  {
    id: 'ch8-2',
    chapter: '8',
    chapterName: '爱与欢乐',
    section: '赢得合作的四个步骤',
    page: '200-205',
    content: '赢得合作的四个步骤：1）表达理解："我知道你很生气/沮丧"；2）表达同情："我也有过类似感受"；3）分享你的感受："但我担心的是..."；4）关注解决问题："你觉得我们怎么解决？"',
    tags: ['赢得合作', '四个步骤', '共情', '解决问题'],
  },
  {
    id: 'ch8-3',
    chapter: '8',
    chapterName: '爱与欢乐',
    section: '鼓励与表扬',
    page: '205-210',
    content: '表扬是评价性的（"你真聪明"），鼓励是欣赏性的（"你的努力有回报了"）。鼓励帮助孩子建立自信，表扬可能导致孩子依赖外部认可。',
    tags: ['鼓励', '表扬', '自尊', '内在动力'],
  },
  {
    id: 'ch8-4',
    chapter: '8',
    chapterName: '爱与欢乐',
    section: '表达无条件的爱',
    page: '210-215',
    content: '孩子需要知道，即使他们做了不好的事情，父母仍然爱他们。重要的是行为，而不是人格。让孩子知道："我爱你，但我不喜欢这个行为。"',
    tags: ['无条件的爱', '行为', '爱', '接纳'],
  },
  {
    id: 'ch8-5',
    chapter: '8',
    chapterName: '爱与欢乐',
    section: '建立亲密关系',
    page: '215-220',
    content: '特别时光能建立亲密关系。每天至少10分钟的全心关注，比一整天的敷衍陪伴更有价值。关掉手机，保持眼神接触，真正"在场"。',
    tags: ['特别时光', '亲密', '关注', '陪伴'],
  },
];

// 默认任务模板
export const defaultTaskTemplates: TaskTemplate[] = [
  // 早晨
  {
    id: 'morning-1',
    period: 'morning',
    title: '起床问候',
    description: '用正面语言叫醒孩子，如"美好的一天开始了，你需要我抱抱还是自己起床？"',
    icon: 'sun',
  },
  {
    id: 'morning-2',
    period: 'morning',
    title: '穿衣整理',
    description: '给孩子有限选择："你想先穿衣服还是先刷牙？"',
    icon: 'shirt',
  },
  {
    id: 'morning-3',
    period: 'morning',
    title: '早餐时光',
    description: '让孩子参与准备："你想帮忙摆碗筷还是准备水果？"',
    icon: 'utensils',
  },
  // 日间
  {
    id: 'afternoon-1',
    period: 'afternoon',
    title: '放学回家',
    description: '情感联结时刻："我好想你！今天发生了什么开心的事吗？"',
    icon: 'home',
  },
  {
    id: 'afternoon-2',
    period: 'afternoon',
    title: '作业时间',
    description: '使用惯例表："作业时间到了，你的惯例表上第一项是什么？"',
    icon: 'book',
  },
  {
    id: 'afternoon-3',
    period: 'afternoon',
    title: '自由活动',
    description: '给孩子自主选择："你有30分钟自由时间，你想做什么？"',
    icon: 'play',
  },
  // 晚间
  {
    id: 'evening-1',
    period: 'evening',
    title: '晚餐准备',
    description: '邀请参与："晚餐需要小帮手，你愿意帮忙吗？"',
    icon: 'chef-hat',
  },
  {
    id: 'evening-2',
    period: 'evening',
    title: '睡前分享',
    description: '特别时光："我们聊聊今天的开心事和挑战吧。今天有什么让你烦恼的吗？"',
    icon: 'moon',
  },
  {
    id: 'evening-3',
    period: 'evening',
    title: '道晚安',
    description: '爱的表达："我爱你。晚安。"（无言信号：摸耳朵）',
    icon: 'heart',
  },
];

// 默认话术卡片 - 扩充版
export const defaultPhraseCards: PhraseCard[] = [
  // 赢得合作
  {
    id: 'phrase-1',
    category: '赢得合作',
    title: '表达理解',
    content: '我知道你很生气/沮丧/难过。',
    situation: '孩子情绪激动时，先表达理解',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['共情', '理解', '情绪'],
  },
  {
    id: 'phrase-2',
    category: '赢得合作',
    title: '表达同情',
    content: '我也有过类似的感觉，当我也...的时候。',
    situation: '建立连接，表明我们也有类似经历',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['共情', '连接', '分享'],
  },
  {
    id: 'phrase-3',
    category: '赢得合作',
    title: '分享感受',
    content: '但我担心的是...，因为...',
    situation: '在理解之后，表达家长的感受',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['表达感受', '担忧', '原因'],
  },
  {
    id: 'phrase-4',
    category: '赢得合作',
    title: '关注解决',
    content: '你觉得我们怎么解决这个问题？',
    situation: '邀请孩子参与解决',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['解决问题', '邀请', '合作'],
  },
  // 启发式提问
  {
    id: 'phrase-5',
    category: '启发式提问',
    title: '了解情况',
    content: '发生了什么事？',
    situation: '不预设答案开放式提问',
    sourceChapter: '第4章',
    isFavorite: false,
    tags: ['开放', '了解', '不预判'],
  },
  {
    id: 'phrase-6',
    category: '启发式提问',
    title: '探究感受',
    content: '你当时有什么感受？',
    situation: '帮助孩子认识情绪',
    sourceChapter: '第4章',
    isFavorite: false,
    tags: ['感受', '情绪', '认识'],
  },
  {
    id: 'phrase-7',
    category: '启发式提问',
    title: '探究原因',
    content: '你觉得为什么会有这种事情发生？',
    situation: '帮助孩子反思原因',
    sourceChapter: '第4章',
    isFavorite: false,
    tags: ['原因', '反思', '分析'],
  },
  {
    id: 'phrase-8',
    category: '启发式提问',
    title: '展望未来',
    content: '下次遇到这种情况，你可以怎么做？',
    situation: '培养解决问题的能力',
    sourceChapter: '第4章',
    isFavorite: false,
    tags: ['未来', '解决方案', '预防'],
  },
  {
    id: 'phrase-9',
    category: '启发式提问',
    title: '学习收获',
    content: '你从中学到了什么？',
    situation: '把错误变成学习机会',
    sourceChapter: '第2章',
    isFavorite: false,
    tags: ['学习', '成长', '反思'],
  },
  // 积极暂停
  {
    id: 'phrase-10',
    category: '积极暂停',
    title: '冷静提议',
    content: '我们都需要冷静一下，等准备好了再谈。',
    situation: '双方情绪激动时',
    sourceChapter: '第4章',
    isFavorite: false,
    tags: ['冷静', '暂停', '重新开始'],
  },
  {
    id: 'phrase-11',
    category: '积极暂停',
    title: '我的感受',
    content: '我现在感觉很激动，我需要冷静一下。',
    situation: '以身作则展示情绪管理',
    sourceChapter: '第4章',
    isFavorite: false,
    tags: ['示范', '情绪管理', '诚实'],
  },
  {
    id: 'phrase-12',
    category: '积极暂停',
    title: '使用暗号',
    content: '（无言信号：摸耳朵 = 我爱你）',
    situation: '创建属于你们的暗号系统',
    sourceChapter: '第7章',
    isFavorite: false,
    tags: ['暗号', '无言', '信号'],
  },
  // 情绪调节
  {
    id: 'phrase-13',
    category: '情绪调节',
    title: '接纳情绪',
    content: '你有权利感到生气/难过/沮丧。',
    situation: '肯定孩子的感受是合理的',
    sourceChapter: '第2章',
    isFavorite: false,
    tags: ['接纳', '情绪', '肯定'],
  },
  {
    id: 'phrase-14',
    category: '情绪调节',
    title: '区分感受与行为',
    content: '你可以感到生气，但打人不可以。',
    situation: '区分感受和行为',
    sourceChapter: '第2章',
    isFavorite: false,
    tags: ['感受', '行为', '界限'],
  },
  {
    id: 'phrase-15',
    category: '情绪调节',
    title: '爱的表达',
    content: '我爱你，但我现在不喜欢你的行为。',
    situation: '无条件的爱 + 行为界限',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['爱', '界限', '无条件'],
  },
  // 错误目的应对
  {
    id: 'phrase-16',
    category: '错误目的',
    title: '应对自暴自弃',
    content: '我看到你很努力，我为你骄傲。哪怕只是一小步，也是一大步。',
    situation: '孩子表现出放弃行为时',
    sourceChapter: '第3章',
    isFavorite: false,
    tags: ['鼓励', '自暴自弃', '肯定努力'],
  },
  {
    id: 'phrase-17',
    category: '错误目的',
    title: '应对寻求权力',
    content: '让我们暂停一下，等我们都冷静了再来解决。',
    situation: '权力之争时',
    sourceChapter: '第3章',
    isFavorite: false,
    tags: ['权力', '退出', '冷静'],
  },
  {
    id: 'phrase-18',
    category: '错误目的',
    title: '应对报复',
    content: '我理解你受伤了。我们可以谈谈吗？',
    situation: '孩子表现出报复行为时',
    sourceChapter: '第3章',
    isFavorite: false,
    tags: ['报复', '理解', '共情'],
  },
  {
    id: 'phrase-19',
    category: '错误目的',
    title: '应对寻求关注',
    content: '我现在很忙，但我很快就专门陪你玩10分钟。',
    situation: '孩子不断寻求关注时',
    sourceChapter: '第3章',
    isFavorite: false,
    tags: ['关注', '特别时光', '承诺'],
  },
  // 日常惯例
  {
    id: 'phrase-20',
    category: '日常惯例',
    title: '惯例表引导',
    content: '你的惯例表上接下来是什么？',
    situation: '代替唠叨和提醒',
    sourceChapter: '第7章',
    isFavorite: false,
    tags: ['惯例表', '引导', '自主'],
  },
  {
    id: 'phrase-21',
    category: '日常惯例',
    title: '有限选择',
    content: '你想穿红色的还是蓝色的衣服？',
    situation: '给予适当的选择权',
    sourceChapter: '第7章',
    isFavorite: false,
    tags: ['选择', '自主', '有限'],
  },
  {
    id: 'phrase-22',
    category: '日常惯例',
    title: '睡前分享开场',
    content: '今天有什么让你开心的事？有什么让你烦恼的吗？',
    situation: '睡前分享时光',
    sourceChapter: '第7章',
    isFavorite: false,
    tags: ['睡前', '分享', '交流'],
  },
  // 家庭会议
  {
    id: 'phrase-23',
    category: '家庭会议',
    title: '致谢开场',
    content: '我想对___说声谢谢，因为___。',
    situation: '家庭会议致谢环节',
    sourceChapter: '第6章',
    isFavorite: false,
    tags: ['致谢', '感激', '家庭会议'],
  },
  {
    id: 'phrase-24',
    category: '家庭会议',
    title: '头脑风暴',
    content: '好主意！我们把所有想法都写下来，之后再评估。',
    situation: '头脑风暴阶段',
    sourceChapter: '第6章',
    isFavorite: false,
    tags: ['头脑风暴', '创意', '不批评'],
  },
  {
    id: 'phrase-25',
    category: '家庭会议',
    title: '邀请参与',
    content: '你觉得有什么办法能让大家都满意？',
    situation: '决策阶段邀请孩子意见',
    sourceChapter: '第6章',
    isFavorite: false,
    tags: ['决策', '邀请', '共识'],
  },
  // 鼓励话语
  {
    id: 'phrase-26',
    category: '鼓励话语',
    title: '描述性鼓励',
    content: '我看到你___（具体行为）。这说明你___（品格）。',
    situation: '描述孩子的具体行为和品格',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['鼓励', '具体', '品格'],
  },
  {
    id: 'phrase-27',
    category: '鼓励话语',
    title: '感激鼓励',
    content: '谢谢你___（具体帮助）。这让我感到___（感受）。',
    situation: '表达感激而非评价',
    sourceChapter: '第8章',
    isFavorite: false,
    tags: ['感激', '具体', '感受'],
  },
  {
    id: 'phrase-28',
    category: '鼓励话语',
    title: '信任表达',
    content: '我相信你能处理好这件事。',
    situation: '表达对孩子能力的信任',
    sourceChapter: '第3章',
    isFavorite: false,
    tags: ['信任', '能力', '鼓励'],
  },
  // 矫正错误
  {
    id: 'phrase-29',
    category: '矫正错误',
    title: '承认错误',
    content: '我犯了一个错误，我很抱歉。',
    situation: '家长犯错时示范',
    sourceChapter: '第2章',
    isFavorite: false,
    tags: ['道歉', '错误', '示范'],
  },
  {
    id: 'phrase-30',
    category: '矫正错误',
    title: '和好',
    content: '我刚才对你太严厉了，我向你道歉。',
    situation: '过度反应后修复关系',
    sourceChapter: '第2章',
    isFavorite: false,
    tags: ['和好', '道歉', '修复'],
  },
];

// 默认孩子档案
export const defaultChildProfile = {
  id: 'child-1',
  name: '小明',
  birthDate: '2018-03-15',
  gender: 'male' as const,
  currentStage: '幼儿园' as const,
  keyBehaviors: [],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
